### ISSUE TITLE
Mac check failed!

### ISSUE THREAD

**Issue by khspace** [tasos-py/AES-Encryption-Classes#1]

**Comment by khspace** [comment]
nodejs：
`let aes=new AesEncryption("cfb",256); aes.decrypt(“123456789”,“123456790123456”);`

**Comment by tasos-py** [comment]
This error message means that the ciphertext or password/key is invalid. When encrypting data the MAC of ciphertext is computed and appended to the ciphertext. When decrypting data the MAC of ciphertext is computed again, and then it is compared with the received MAC to verify the authenticity of the ciphertext. If this check fails an exception is raised and decryption is aborted. If you think the ciphertext and password are correct, please provide enough details so that I can reproduce the error.
